version: '3'
services:
    mysql:
        image: mariadb:10
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
            MYSQL_DATABASE: todoapi
            MYSQL_USER: todoapi
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - mysqldb:/var/lib/mysql
        ports:
            - "3306:3306"
volumes:
  mysqldb: