version: '3'
services:
    todoapi:
        build:
            context: ./todoapi
        ports:
            - "5000:80"
        environment:
            MYSQL_HOST: mysql
        depends_on:
            - mysql
    mysql:
        image: mariadb:10
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
            MYSQL_DATABASE: todoapi
            MYSQL_USER: todoapi
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - mysqldb:/var/lib/mysql
volumes:
  mysqldb: